---
name: changes

"on":
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19.0

      - name: Run changelog
        id: changelog
        run: make changelog

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: CHANGELOG.md
          message: "docs: automated changelog update"
          push: true
          commit: --signoff

  envvars:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19.0

      - name: Generate envvars
        id: envvars
        run: make envvars

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: docs/partials/envvars.md
          message: "docs: automated envvars update"
          push: true
          commit: --signoff

  metrics:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19.0

      - name: Generate metrics
        id: metrics
        run: make metrics

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: docs/partials/metrics.md
          message: "docs: automated metrics update"
          push: true
          commit: --signoff

...
